### ISSUE TITLE
Bug - Flyte binary pod keeps crashing

### ISSUE THREAD

**Issue by Maximilien22** [davidmirror-ops/flyte-the-hard-way#19]
I had an issue with the tutorial "Flyte on local Kubernetes"

While installing flyte as a single librairy, the flyte binary would keep crashing.

I solved this issue by : 

1. Changing line 3 in my value file : 

username: postgres -> username: flyte

2. Adding in my secret.yaml (above the password line) :
user: "flyte"

**Comment by brandli** [comment]
Great! Just saw this and it fixed my connection issue but now my pod keeps crashing with following message:

```
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/manager/internal.go:514 +0x258
{"json":{"src":"start.go:226"},"level":"panic","msg":"Failed to start Propeller, err: failed to create FlyteWorkflow CRD: Post \"https://10.152.183.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions?timeout=30s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)","ts":"2024-07-15T10:33:10Z"}
panic: (*logrus.Entry) 0xc0006f0ee0
goroutine 146 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0006f0e00, 0x0, {0xc003db1d40, 0x110})
 /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x491
github.com/sirupsen/logrus.(*Entry).Log(0xc0006f0e00, 0x0, {0xc0017a1e68?, 0x1?, 0x1?})
 /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
github.com/sirupsen/logrus.(*Entry).Logf(0xc0006f0e00, 0x0, {0x34d6a61?, 0x0?}, {0xc0040a67b0?, 0x0?, 0x0?})
 /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0x7c
github.com/sirupsen/logrus.(*Entry).Panicf(0x4360f40?, {0x34d6a61?, 0x414325?}, {0xc0040a67b0?, 0x2cf9f20?, 0x1?})
 /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:387 +0x2e
github.com/flyteorg/flyte/flytestdlib/logger.Panicf({0x4360f40?, 0xc000697ef0?}, {0x34d6a61, 0x22}, {0xc0040a67b0, 0x1, 0x1})
 /flyteorg/build/flytestdlib/logger/logger.go:189 +0x5e
github.com/flyteorg/flyte/cmd/single.glob..func4.2()
 /flyteorg/build/cmd/single/start.go:226 +0xb1
golang.org/x/sync/errgroup.(*Group).Go.func1()
 /go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
 /go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96
```

No clue what this is or what to do about it. Any idea?

**Comment by davidmirror-ops** [comment]
@Maximilien22 there's got to be something wrong with my Github notifications that I missed this one. Sorry.
Will work on fixing all these issues

**Comment by davidmirror-ops** [comment]
The mismatch in the Postgres user name between the Helm values and the db deployment was fixed. Please report any further issues

Thanks for your patience
